=== lambertmukudzei/Bookshop-Group-Project/Bookshop-Group-Project-main/Bookshop-Group-Project-main/books.dtd
000<!-- ============================================ -->
<!-- DTD FOR PAGETURNER BOOKSHOP         -->
<!-- CST1340 - Information in Organisations       -->
<!-- Student: Mukudzei Kunyetu-Lambert            -->
<!-- Student ID: M01061702                        -->
<!-- Date: 31 March 2026                          -->
<!-- ============================================ -->
<!-- This DTD validates the XML structure in our books.xml file -->
<!-- It defines what elements are allowed and in what order -->
<!-- ============================================ -->

<!-- ============================================ -->
<!-- 1. The ROOT ELEMENT                              -->
<!-- ============================================ -->
<!-- library is the root element of our XML document -->
<!-- It must contain one or more category elements -->
<!-- The + symbol means "one or more" - so at least one category is required -->
<!ELEMENT library (category+)>

<!-- ============================================ -->
<!-- 2.The CATEGORY ELEMENT                          -->
<!-- ============================================ -->
<!-- Each category contains one or more book elements -->
<!-- For example: Cooking, Fantasy, Romance, Horror, Children -->
<!-- The + symbol again means each category must have at least one book -->
<!ELEMENT category (book+)>

<!-- Category has a required name attribute -->
<!-- CDATA means it can contain any text data -->
<!-- #REQUIRED means this attribute MUST be present for every category -->
<!ATTLIST category
    name CDATA #REQUIRED
>

<!-- ============================================ -->
<!-- 3. The BOOK ELEMENT                              -->
<!-- ============================================ -->
<!-- Each book contains all book information in this exact order -->
<!-- The order matters - XML must follow: ISBN, image, Title, etc. -->
<!-- If elements are out of order, the DTD will show an error -->
<!ELEMENT book (ISBN, image, Title, Author, Publisher, edition, date, price)>

<!-- ============================================ -->
<!-- 4. The SIMPLE TEXT ELEMENTS                      -->
<!-- ============================================ -->
<!-- These elements contain plain text only -->
<!-- #PCDATA stands for "Parsed Character Data" - just regular text content -->
<!ELEMENT ISBN (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Publisher (#PCDATA)>
<!ELEMENT edition (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT price (#PCDATA)>

<!-- ============================================ -->
<!-- 5. The AUTHOR ELEMENT (NESTED STRUCTURE)         -->
<!-- ============================================ -->
<!-- Author is a container element - it holds firstName and lastName -->
<!-- This creates a nested structure inside each book -->
<!-- Elements must appear in this order: firstName THEN lastName -->
<!ELEMENT Author (firstName, lastName)>

<!-- These are the individual author name components -->
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>

<!-- ============================================ -->
<!-- SUMMARY OF WHAT THIS DTD DOES:               -->
<!-- ============================================ -->
<!-- 1. Ensures every library has at least one category -->
<!-- 2. Ensures every category has a name attribute -->
<!-- 3. Ensures every category has at least one book -->
<!-- 4. Ensures every book has all 8 elements in correct order -->
<!-- 5. Ensures every book has an author with first and last name -->
<!-- 6. Ensures all text elements contain plain text only -->
<!-- ============================================ -->

=== lambertmukudzei/Bookshop-Group-Project/1340.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="bks.xsl"?>
<!DOCTYPE library SYSTEM "books.dtd">

<library>

  <category name="Cooking">
    <book>
      <ISBN>095-56473907</ISBN>
      <image>saltfatacid.jpg</image>
      <Title>Salt, Fat, Acid, Heat: Mastering the Elements of Good Cooking </Title>
      <Author>
        <lastName>Nosrat</lastName>
        <firstName>Samin</firstName>
      </Author>
      <Publisher>FoodPress</Publisher>
      <edition>First</edition>
      <date>2020</date>
      <price>157.99</price>
    </book>

    <book>
      <ISBN>987-87046583</ISBN>
      <image>foodlab.png</image>
      <Title>The Food Lab: Better Home Cooking Through Science </Title>
      <Author>
        <lastName>Lopez</lastName>
        <firstName>Kenji</firstName>
      </Author>
      <Publisher>GourmetHouse</Publisher>
      <edition>Second</edition>
      <date>2019</date>
      <price>272.50</price>
    </book>

    <book>
      <ISBN>567-59205638</ISBN>
      <image>kingarthur.jpg</image>
      <Title>King Arthur Baking School: Lessons and Recipes for Every Baker </Title>
      <Author>
        <lastName>King</lastName>
        <firstName>Arthur</firstName>
      </Author>
      <Publisher>SweetBooks</Publisher>
      <edition>First</edition>
      <date>2021</date>
      <price>188.00</price>
    </book>

    <book>
      <ISBN>896-860375794</ISBN>
      <image>bakingbible.jpg</image>
      <Title>The Baking Bible </Title>
      <Author>
        <lastName>Beranbaum</lastName>
        <firstName>Rose</firstName>
      </Author>
      <Publisher>SweetBooks</Publisher>
      <edition>First</edition>
      <date>2021</date>
      <price>180.00</price>
    </book>

    <book>
      <ISBN>509-</ISBN>
      <image>joycooking.jpg</image>
      <Title>The Joy of Cooking </Title>
      <Author>
        <lastName>Rombauer</lastName>
        <firstName>Irma</firstName>
      </Author>
      <Publisher>CookBooks</Publisher>
      <edition>Third</edition>
      <date>2005</date>
      <price>108.00</price>
    </book>

  </category>

  <category name="Fantasy">
    <book>
      <ISBN>696-40782569</ISBN>
      <image>acotar.jpg</image>
      <Title>A Court Of Thorns and Roses</Title>
      <Author>
        <lastName>Maas</lastName>
        <firstName>Sarah</firstName>
      </Author>
      <Publisher>MagicHouse</Publisher>
      <edition>First</edition>
      <date>2018</date>
      <price>250.50</price>
    </book>

    <book>
      <ISBN>450-306583957</ISBN>
      <image>kingdomash.jpg</image>
      <Title>Kingdom of Ash</Title>
      <Author>
        <lastName>Maas</lastName>
        <firstName>Sarah</firstName>
      </Author>
      <Publisher>FantasyWorks</Publisher>
      <edition>Second</edition>
      <date>2020</date>
      <price>207.99</price>
    </book>

    <book>
      <ISBN>456-95023006</ISBN>
      <image>fourthwing.jpg</image>
      <Title>Fourth Wing</Title>
      <Author>
        <lastName>Yarros</lastName>
        <firstName>Rebecca</firstName>
      </Author>
      <Publisher>EpicReads</Publisher>
      <edition>First</edition>
      <date>2022</date>
      <price>908.99</price>
    </book>

    <book>
      <ISBN>001-86047691</ISBN>
      <image>thewitcher.jpg</image>
      <Title>The Witcher</Title>
      <Author>
        <lastName>Sapkowski</lastName>
        <firstName>Andrzej</firstName>
      </Author>
      <Publisher>EpicReads</Publisher>
      <edition>First</edition>
      <date>2022</date>
      <price>698.99</price>
    </book>

    <book>
      <ISBN>043-94871323</ISBN>
      <image>sandman.jpg</image>
      <Title>The Sandman</Title>
      <Author>
        <lastName>Gaiman</lastName>
        <firstName>Nei</firstName>
      </Author>
      <Publisher>EpicReads</Publisher>
      <edition>First</edition>
      <date>1992</date>
      <price>298.99</price>
    </book>
  </category>

  <category name="Romance">
    <book>
      <ISBN>333-3333333331</ISBN>
      <image>hypothesis.jpg</image>
      <Title>The Love Hypothesis</Title>
      <Author>
        <lastName>Hazelwood</lastName>
        <firstName>Ali</firstName>
      </Author>
      <Publisher>HeartBooks</Publisher>
      <edition>First</edition>
      <date>2021</date>
      <price>708.75</price>
    </book>

    <book>
      <ISBN>333-3333333332</ISBN>
      <image>rwrb.jpg</image>
      <Title>Red White and Royal Blue</Title>
      <Author>
        <lastName>McQuinston</lastName>
        <firstName>Casey</firstName>
      </Author>
      <Publisher>RomancePress</Publisher>
      <edition>Second</edition>
      <date>2019</date>
      <price>160.50</price>
    </book>

    <book>
      <ISBN>333-3333333333</ISBN>
      <image>endsus.jpg</image>
      <Title>It Ends with Us</Title>
      <Author>
        <lastName>Hoover</lastName>
        <firstName>Colleen</firstName>
      </Author>
      <Publisher>LoveStories Inc.</Publisher>
      <edition>First</edition>
      <date>2020</date>
      <price>197.99</price>
    </book>

    <book>
      <ISBN>333-3333333334</ISBN>
      <image>husbands.jpg</image>
      <Title>The Seven Husbands of Evelyn Hugo</Title>
      <Author>
        <lastName>Reid</lastName>
        <firstName>Taylor Jenkins</firstName>
      </Author>
      <Publisher>LoveStories Inc.</Publisher>
      <edition>First</edition>
      <date>2020</date>
      <price>457.99</price>
    </book>

    <book>
        <ISBN>333-3333333335</ISBN>
        <image>viscount.jpg</image>
        <Title>The Viscount Who Loved Me</Title>
        <Author>
            <lastName>Quinn</lastName>
            <firstName>Julia</firstName>
        </Author>
        <Publisher>RomancePress</Publisher>
        <edition>First</edition>
        <date>2018</date>
        <price>697.99</price>
    </book>
 </category>

  <category name="Horror">
    <book>
      <ISBN>444-4444444441</ISBN>
      <image>goosebumps.jpg</image>
      <Title>Goosebumps</Title>
      <Author>
        <lastName>Stine</lastName>
        <firstName>RL</firstName>
      </Author>
      <Publisher>DarkHouse</Publisher>
      <edition>First</edition>
      <date>2017</date>
      <price>240.00</price>
    </book>

    <book>
      <ISBN>444-4444444442</ISBN>
      <image>frankestein.jpg</image>
      <Title>Frankenstein</Title>
      <Author>
        <lastName>Shelley</lastName>
        <firstName>Mary</firstName>
      </Author>
      <Publisher>FearPress</Publisher>
      <edition>Second</edition>
      <date>2019</date>
      <price>250.75</price>
    </book>

    <book>
      <ISBN>444-4444444443</ISBN>
      <image>exorcist.jpg</image>
      <Title>The Exorcist</Title>
      <Author>
        <lastName>Blatty</lastName>
        <firstName>William Peter</firstName>
      </Author>
      <Publisher>NightReads</Publisher>
      <edition>First</edition>
      <date>2021</date>
      <price>230.50</price>
    </book>

    <book>
        <ISBN>444-4444444444</ISBN>
        <image>dracula.jpg</image>
        <Title>Dracula</Title>
        <Author>
            <lastName>Stoker</lastName>
            <firstName>Bram</firstName>
        </Author>
        <Publisher>FearPress</Publisher>
        <edition>First</edition>
        <date>1897</date>
        <price>150.00</price>
    </book>

    <book>
        <ISBN>444-4444444445</ISBN>
        <image>it.jpg</image>
        <Title>It</Title>
        <Author>
            <lastName>King</lastName>
             <firstName>Stephen</firstName>
        </Author>
        <Publisher>NightReads</Publisher>
        <edition>First</edition>
        <date>1986</date>
        <price>120.00</price>
    </book>

  </category>

  <category name="Children">
    <book>
      <ISBN>555-5555555551</ISBN>
      <image>pinocchio.jpg</image>
      <Title>Pinocchio</Title>
      <Author>
        <lastName>Collodi</lastName>
        <firstName>Carlo</firstName>
      </Author>
      <Publisher>KidsWorld</Publisher>
      <edition>First</edition>
      <date>2018</date>
      <price>125.99</price>
    </book>

    <book>
      <ISBN>555-5555555552</ISBN>
      <image>wild.jpg</image>
      <Title>Where the Wild Things Are</Title>
      <Author>
        <lastName>Sendak</lastName>
        <firstName>Maurice</firstName>
      </Author>
      <Publisher>ChildrenBooks Inc.</Publisher>
      <edition>Second</edition>
      <date>2019</date>
      <price>150.50</price>
    </book>

    <book>
      <ISBN>555-5555555553</ISBN>
      <image>charlotte.jpg</image>
      <Title>Charlotte's Web</Title>
      <Author>
        <lastName>White</lastName>
        <firstName>E.B.</firstName>
      </Author>
      <Publisher>KidsWorld</Publisher>
      <edition>First</edition>
      <date>2020</date>
      <price>200.00</price>
    </book>

    <book>
        <ISBN>555-5555555554</ISBN>
        <image>matilda.jpg</image>
        <Title>Matilda</Title>
        <Author>
            <lastName>Dahl</lastName>
            <firstName>Roald</firstName>
        </Author>
        <Publisher>ChildrenBooks Inc.</Publisher>
        <edition>First</edition>
        <date>1988</date>
        <price>180.00</price>
    </book>

    <book>
        <ISBN>555-5555555555</ISBN>
        <image>caterpilar.jpg</image>
        <Title>The Very Hungry Caterpillar</Title>
        <Author>
            <lastName>Carle</lastName>
            <firstName>Eric</firstName>
        </Author>
        <Publisher>KidsWorld</Publisher>
        <edition>First</edition>
        <date>1969</date>
        <price>1000.00</price>
    </book>


  </category>

</library>
